development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin    
  host: localhost
  database: crud
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin    
  host: localhost
  database: crud
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin    
  host: localhost
  database: crud
  port: 5432